SELECT MVTITLE, DIRNUMB FROM MOVIE;


SELECT MOVIE.MVTITLE, DIRECTOR.DIRNAME, DIRECTOR.DIRNUMB
FROM MOVIE JOIN DIRECTOR
ON MOVIE.DIRNUMB = DIRECTOR.DIRNUMB;


SELECT mov.MVTITLE, dir.DIRNAME --, mov.DIRNUMB AS MOVdirnumb, dir.DIRNUMB as DIRdirnumb
FROM MOVIE mov JOIN DIRECTOR dir -- alias
ON mov.DIRNUMB = dir.DIRNUMB; -- Foreign key == Primary key


SELECT mov.MVTITLE, dir.DIRNAME --, mov.DIRNUMB AS MOVdirnumb, dir.DIRNUMB as DIRdirnumb
FROM MOVIE mov JOIN DIRECTOR dir -- alias
ON mov.DIRNUMB = dir.DIRNUMB
WHERE dir.DIRNAME LIKE '%Stanley' -- % : wildcard
;


SELECT br.TXNUMB, br.MVNUMB, br.BORDTE, br.MMBNUMB, mov.MVTITLE, mem.MMBNAME
FROM (BORROW br JOIN MOVIE mov
        ON br.MVNUMB = mov.MVNUMB)
        JOIN MEMBER mem
            ON br.MMBNUMB = mem.MMBNUMB;


